### ISSUE TITLE
Missed OP

### ISSUE THREAD

**Issue by vh21** [ARM-software/android-nn-driver#1]
I tried to run tflitedemo example and found the message,
```
ArmnnDriver: ConvertConv2d: not supported by armnn
```
Will you have the plan to add it?

**Comment by MatthewARM** [comment]
Hi @vh21 that would depend on the model that you using. CONV_2D is supported by the driver except for certain combinations of parameters which are documented in ReleaseNotes.txt. In any case, this should not cause incorrect operation of your application, as the Android NN framework will run the operation on its built-in optimised CPU path.

**Comment by MatthewARM** [comment]
Hi @vh21 I hope this has answered your question.
