### ISSUE TITLE
How much memory consumption between 18.03-18.05 and 18.05-18.08?

### ISSUE THREAD

**Issue by uikilin100** [ARM-software/android-nn-driver#10]
In 18.05 release note, there is 
"In general, the amount of RAM needed for a loaded network has been reduced by 20-30% compared to release 18.03."

And in 18.08 release note, there is
"This release of Arm NN integrates the latest Compute Library and adds improvements to thread-safety, memory consumption and overall performance."

I got information about memory usage in issue:
https://github.com/ARM-software/android-nn-driver/issues/8

But when I tried in 18.05, it looks like more than 2 * model size.
What version should I use to get better memory usage?

**Comment by MatthewARM** [comment]
Hi @uikilin100 you should always use the latest version. At the moment that is 19.05.

Hope that helps,
Matthew

**Comment by MatthewARM** [comment]
@uikilin100 I'll close this issue, please reopen it or create a new one if you are still having trouble with memory consumption. I hope things are going well for you.
