### ISSUE TITLE
question about the schedule for the next release

### ISSUE THREAD

**Issue by youngilesam** [ARM-software/android-nn-driver#11]
Hi ARM-software,

Is the support for android NN hal v1.2 in the next release?
Then, what's your schedule?

Regards
HJ

**Comment by MatthewARM** [comment]
Hi @youngilesam HAL 1.2 is supported in the current v19.08 release, you can see the supported features in the release notes here: https://github.com/ARM-software/android-nn-driver/releases/tag/v19.08 is there anything in particular you need?
