### ISSUE TITLE
getType always returns CPU

### ISSUE THREAD

**Issue by MatthewARM** [ARM-software/android-nn-driver#16]
In getType() at:

https://github.com/ARM-software/android-nn-driver/blob/7e4f7b181908478b3f9c0a23dd4a26b476542e30/1.2/ArmnnDriver.hpp#L133
and
https://github.com/ARM-software/android-nn-driver/blob/7e4f7b181908478b3f9c0a23dd4a26b476542e30/1.3/ArmnnDriver.hpp#L248

they always return DeviceType::CPU, whereas they should return 'Other' (for a heterogenous interface) or check the service startup flags to find out which backend is preferred (e.g. GPU).

**Comment by MatthewARM** [comment]
See: https://source.android.com/devices/neural-networks/device-discovery#implement

"Other" might be hard to implement - it says "A driver with a heterogeneous interface should also expose separate IDevice interfaces that correspond to individual devices to allow an application to choose from those devices."

**Comment by Deweyave** [comment]
@jameo

**Comment by Deweyave** [comment]
> @Jameo

https://github.com/ARM-software/android-nn-driver/issues/16#issuecomment-1370644673

**Comment by Deweyave** [comment]
> @Jameo
