### ISSUE TITLE
Is libOpenCL an absolute requirement?

### ISSUE THREAD

**Issue by poweif** [ARM-software/android-nn-driver#17]
Are there perhaps ways to build on vulkan or just plain OpenGL?

Thanks

**Comment by poweifeng** [comment]
I see. thank you for the response. And I suppose implementing a Vulkan or GL-based runtime is not on the roadmap for android-nn-driver?

**Comment by poweif** [comment]
Thank you for the response.  And a Vulkan or GL-based implementation is not on the roadmap?
