### ISSUE TITLE
 Is there a way to use android-nn-driver on existing smartphones?

### ISSUE THREAD

**Issue by nadongguri** [ARM-software/android-nn-driver#6]
Hi ARM-software,

I have a question about ARM HAL driver (android.hardware.neuralnetworks@1.1-service-armnn).
(I am new to the Android build system. So my question would be trivial.)
I refered to #2  and #4.

I have a galaxy s10+ device and I'd like to run tf-lite with ARM GPU by using android-nn-api path. In order to accelerate ARM GPU by using android-nn-api on smart phones, do I have to build this android-nn-driver in manual? (Isn't there prebuilt android-nn-driver?)
I'm also wondering it's possible to copy this driver(android.hardware.neuralnetworks@1.1-service-armnn) to the existing target without flashing full image.

Regards,
Dongjin.

**Comment by MatthewARM** [comment]
Hi @nadongguri it's hard to answer with specifics. I don't know what drivers Samsung include in the S10+, but perhaps you could run an NNAPI benchmark to find out what the performance is of the NNAPI on your phone?

Copying the driver might work, you would also need to run it, and I suspect you would have to root the phone in order to get it working correctly.

**Comment by nadongguri** [comment]
Hi @MatthewARM, thanks for your comment.
I ran the TF-lite sample on the galaxy s10+. This sample app provides a mode to choose which backends to use such as GLES compute, NN-API or CPU. I don't know which nn-api backend this device uses but it seems using CPU.

As you said, I will try to root this device first, then build this driver. :)
And I have one more question. As you pointed out in #4 , is opencl source code required in order to build this driver? Or can I use libOpenCL.so in the target?

**Comment by MatthewARM** [comment]
Rooting the phone should really be a last resort as it may make other stuff break...

**Comment by nadongguri** [comment]
Hi @MatthewARM, I agree. I don't want to root the device but there's no way to copy HAL driver to the vendor partition without permission, though..

As you commented in another issue, you tested this driver on hikey 960 and rooted phone right?
I got AOSP source then set lunch as hikey960-userdebug, then followed the installation guide but some issues were coming.

1. vendor/arm/android-nn-driver/Android.mk: error: libarmnn-driver@1.0: LOCAL_MODULE_TAGS := eng is obsolete. -> commented that macro, solved

2. vendor/arm/android-nn-driver/Android.mk: error: "android.hardware.neuralnetworks@1.0-service-armnn (EXECUTABLES android-arm) missing libOpenCL (SHARED_LIBRARIES android-arm)" 
-> Is it right to place libOpenCL.so in /prebuilts/vndk/* folder?

**Comment by MatthewARM** [comment]
Hi @nadongguri I'm sorry I don't really know the answer to that question, this step is usually performed by a phone vendor when preparing the Android OS for their device. I'm not sure how to make it work for an AOSP community build.
That being said, I would presume that after adding it to a library directory somewhere, you would probably need to declare it from a .mk or a .bp file so that the build file for android-nn-driver knows where to find it.  Maybe there is some documentation somewhere in the AOSP project for how to import a prebuilt library?
Yet another alternative is that the Compute Library has the source code to build 'stub' libOpenCL.so that can be used just for linking, then when your program runs on the target device it can use the proper OpenCL from the system. However, in the Android build environment we don't provide a build file for the stub OpenCL, but you could try to add one? The sources would be in clframework/opencl-1.2-stubs

**Comment by nadongguri** [comment]
Hi @MatthewARM, as your guide. I could build libOpenCL.so in android-nn-driver by using opencl-1.2-stubs. Thanks! And then I got some minor errors then these were avoided by adding wno flags in Android.mk but finally I got clang errors as follows. (I added -v option.)

PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r353983b/bin/clang++ -v -c -Ivendor/arm/android-nn-driver/clframework -Ivendor/arm/android-nn-driver/clframework/include -Ivendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core -Ivendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core/CL -Ivendor/arm/android-nn-driver/clframework/arm_compute/core/NEON/kernels/assembly -Ivendor/arm/android-nn-driver -D__ANDROID_API__=__ANDROID_API_FUTURE__ -D__ANDROID_VNDK__  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a -Iexternal/libcxx/include -Iexternal/libcxxabi/include -isystem out/soong/.intermediates/bionic/libc/libc.llndk/android_arm64_armv8-a_cortex-a73_vendor_shared/gen/include -isystem bionic/libc/kernel/android/uapi -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64  -Wall -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -fPIC -D_USING_LIBCXX -std=gnu++17 -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden -std=c++14 -fexceptions -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -DARM_COMPUTE_CPP_SCHEDULER -Wno-unused-parameter -DNO_DOT_IN_TOOLCHAIN -no-integrated-as -frtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-enum-compare -Wno-enum-compare-switch -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -MD -MF out/soong/.intermediates/vendor/arm/android-nn-driver/armnn-arm_compute/android_arm64_armv8-a_cortex-a73_vendor_static/obj/vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.o.d -o out/soong/.intermediates/vendor/arm/android-nn-driver/armnn-arm_compute/android_arm64_armv8-a_cortex-a73_vendor_static/obj/vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.o vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.cpp
Android (5407736 based on r353983b) clang version 9.0.2 (https://android.googlesource.com/toolchain/clang 649b4adfc45b26ae937fe597ef6134d244f89686) (https://android.googlesource.com/toolchain/llvm 45936e9d187aaac2b7c0245f6f8c10138f6a02e9) (based on LLVM 9.0.2svn)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: prebuilts/clang/host/linux-x86/clang-r353983b/bin
 "prebuilts/clang/host/linux-x86/clang-r353983b/bin/clang++.real" -cc1 -triple aarch64-unknown-linux-android -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name AccessWindowAutoPadding.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -relaxed-aliasing -masm-verbose -no-integrated-as -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -mllvm -aarch64-fix-cortex-a53-835769=1 -fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections -coverage-notes-file /proc/self/cwd/out/soong/.intermediates/vendor/arm/android-nn-driver/armnn-arm_compute/android_arm64_armv8-a_cortex-a73_vendor_static/obj/vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.gcno -nostdsysteminc -resource-dir prebuilts/clang/host/linux-x86/clang-r353983b/lib64/clang/9.0.2 -dependency-file out/soong/.intermediates/vendor/arm/android-nn-driver/armnn-arm_compute/android_arm64_armv8-a_cortex-a73_vendor_static/obj/vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.o.d -MT out/soong/.intermediates/vendor/arm/android-nn-driver/armnn-arm_compute/android_arm64_armv8-a_cortex-a73_vendor_static/obj/vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.o -sys-header-deps -isystem out/soong/.intermediates/bionic/libc/libc.llndk/android_arm64_armv8-a_cortex-a73_vendor_shared/gen/include -isystem bionic/libc/kernel/android/uapi -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -I vendor/arm/android-nn-driver/clframework -I vendor/arm/android-nn-driver/clframework/include -I vendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core -I vendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core/CL -I vendor/arm/android-nn-driver/clframework/arm_compute/core/NEON/kernels/assembly -I vendor/arm/android-nn-driver -D __ANDROID_API__=__ANDROID_API_FUTURE__ -D __ANDROID_VNDK__ -D ANDROID -D NDEBUG -U DEBUG -D __compiler_offsetof=__builtin_offsetof -D _FORTIFY_SOURCE=2 -I external/libcxx/include -I external/libcxxabi/include -D ANDROID_STRICT -D _USING_LIBCXX -D _LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D EMBEDDED_KERNELS -D ARM_COMPUTE_ASSERTS_ENABLED -D ARM_COMPUTE_CPP_SCHEDULER -D NO_DOT_IN_TOOLCHAIN -internal-isystem prebuilts/clang/host/linux-x86/clang-r353983b/lib64/clang/9.0.2/include -O2 -Werror=implicit-function-declaration -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wno-multichar -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -Wall -Wsign-promo -Wno-thread-safety-negative -Wno-gnu-include-next -Wno-unused-parameter -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-enum-compare -Wno-enum-compare-switch -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -std=c++14 -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir /proc/self/cwd -fdebug-prefix-map=/proc/self/cwd= -ferror-limit 19 -fmessage-length 0 -fvisibility-inlines-hidden -stack-protector 2 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/AccessWindowAutoPadding-ec7249.s -x c++ vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.cpp -faddrsig
clang -cc1 version 9.0.2 based upon LLVM 9.0.2svn default target x86_64-unknown-linux-gnu
#include "..." search starts here:
#include <...> search starts here:
 vendor/arm/android-nn-driver/clframework
 vendor/arm/android-nn-driver/clframework/include
 vendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core
 vendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core/CL
 vendor/arm/android-nn-driver/clframework/arm_compute/core/NEON/kernels/assembly
 vendor/arm/android-nn-driver
 external/libcxx/include
 external/libcxxabi/include
 out/soong/.intermediates/bionic/libc/libc.llndk/android_arm64_armv8-a_cortex-a73_vendor_shared/gen/include
 bionic/libc/kernel/android/uapi
 bionic/libc/kernel/uapi
 bionic/libc/kernel/uapi/asm-arm64
 prebuilts/clang/host/linux-x86/clang-r353983b/lib64/clang/9.0.2/include
End of search list.
 "prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin/as" -EL -march=armv8-a -I vendor/arm/android-nn-driver/clframework -I vendor/arm/android-nn-driver/clframework/include -I vendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core -I vendor/arm/android-nn-driver/clframework/build/android-arm64v8a/src/core/CL -I vendor/arm/android-nn-driver/clframework/arm_compute/core/NEON/kernels/assembly -I vendor/arm/android-nn-driver -I external/libcxx/include -I external/libcxxabi/include --noexecstack -o out/soong/.intermediates/vendor/arm/android-nn-driver/armnn-arm_compute/android_arm64_armv8-a_cortex-a73_vendor_static/obj/vendor/arm/android-nn-driver/clframework/src/core/AccessWindowAutoPadding.o /tmp/AccessWindowAutoPadding-ec7249.s
/tmp/AccessWindowAutoPadding-ec7249.s: Assembler messages:
/tmp/AccessWindowAutoPadding-ec7249.s:15825: Error: unknown pseudo-op: `.addrsig'
/tmp/AccessWindowAutoPadding-ec7249.s:15826: Error: unknown pseudo-op: `.addrsig_sym'
/tmp/AccessWindowAutoPadding-ec7249.s:15827: Error: unknown pseudo-op: `.addrsig_sym'
/tmp/AccessWindowAutoPadding-ec7249.s:15828: Error: unknown pseudo-op: `.addrsig_sym'
/tmp/AccessWindowAutoPadding-ec7249.s:15829: Error: unknown pseudo-op: `.addrsig_sym'
/tmp/AccessWindowAutoPadding-ec7249.s:15830: Error: unknown pseudo-op: `.addrsig_sym'
/tmp/AccessWindowAutoPadding-ec7249.s:15831: Error: unknown pseudo-op: `.addrsig_sym'
/tmp/AccessWindowAutoPadding-ec7249.s:15832: Error: unknown pseudo-op: `.addrsig_sym'
clang++: error: assembler command failed with exit code 1 (use -v to see invocation)

I'm wondering if you have ever seen this error before... There are 10 clang++s in prebuilt but returned the same error.
./clang-r346389b/bin/clang++
./clang-r328903/bin/clang++
./clang-r353983b/bin/clang++
./clang-r346389c/bin/clang++
./clang-r344140b/bin/clang++
./clang-r349610b/bin/clang++
./clang-r353983/bin/clang++
./clang-3289846/bin/clang++
./clang-r339409b/bin/clang++
./clang-r349610/bin/clang++

(I could build sample nn driver in /frameworks/ml/nn/driver/sample by using 'mm' command.)

**Comment by MatthewARM** [comment]
Hi @nadongguri sorry for the delay, I somehow missed your last message.

To clarify, are you seeing two problems:

1. "mm" doesn't build android.hardware.neuralnetworks@1.1-service-armnn
I think this could be due to the PLATFORM_VERSION being too low for neuralnetworks HAL 1.1. Please could you the config options that are displayed when you type "make", e.g.:
`android$ make
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=hikey960
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
`
etc.

2. Error: unknown pseudo-op: `.addrsig'. I've not seen this before, but I suspect it might be because the assembler is too old. My suggestion for this is to try to ask for help from the AOSP developer community, as someone else might have seen something like that.

**Comment by MatthewARM** [comment]
Hi @nadongguri 

For 2. Error: unknown pseudo-op: `.addrsig' it seems this is because we are using the gnu assembler for Compute Library. The fix is to add "-fno-addrsig" to the compiler options for Compute Library. We'll be fixing this on the master branch soon.

**Comment by nadongguri** [comment]
Hi @MatthewARM, thanks for your comments.
Those errors were due to the wrong PLATFORM_VERSION, honestly... I was using the latest AOSP source so PLATOFRM_VERSION was android q. It made tons of errors. Anyway, I could remove all the errors by adding flags or commenting source code but when I made the PLATFORM_VERSION right then there were no errors during the build.
I think you can close this issue. :)

**Comment by MatthewARM** [comment]
Many thanks.
