### ISSUE TITLE
Questions about Android Q support

### ISSUE THREAD

**Issue by youngilesam** [ARM-software/android-nn-driver#7]
Hi ARM-software,

I'm using android-nn-driver well until Android P.
However, it is not possible to build in the Android Q recently.
Do you have any plans to support the Android Q? When?

Regards
HJ

**Comment by MatthewARM** [comment]
Hi @youngilesam We're working hard on that, it will be working in our next release, scheduled for May.

Hope that helps,
Matthew

**Comment by youngilesam** [comment]
Thank you for your answer. :+1:
